### ISSUE TITLE
this.subject => this.owner.lookup

### ISSUE THREAD

**Issue by jbryson3** [ember-codemods/ember-mocha-codemods#107]
Is there a codemod that currently handles transitioning `this.subject()` syntax to `this.owner.lookup()` syntax? I believe I saw one in the ember-qunit-codemods repo that did something like that.

Example Before
```js
setupTest('export:audience-definitions', {
  needs: ['service:retry']
});
//...
let subject = this.subject({ analysis: zeroAudienceAnalysis });
```

Example After
```js
setupTest();
//...
let subject = this.owner.lookup('export:audience-definitions');
subject.set('analysis', zeroAudienceAnalysis);
```

**Comment by pangratz** [comment]
The one linked to in https://github.com/ember-codemods/ember-mocha-codemods#testing-api-beginning-in-014 should cover this, so basically via https://github.com/ember-codemods/ember-mocha-codemods/blob/90451be10db7fcf5ad7f927d2a5feee413f74e7d/fourteen-testing-api.js#L444

**Comment by jbryson3** [comment]
Thanks!
